/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 bag.glb --transform 
Files: bag.glb [13.01MB] > C:\Users\HP\Desktop\New folder (5)\public\3d model\bag-transformed.glb [1.29MB] (90%)
Author: alitural (https://sketchfab.com/alitural)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chanel-leather-bag-for-women-76b020e7137b4293b09b66c26091f42f
Title: Chanel Leather Bag for Women
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";

export function BagModel(props) {
  const { nodes, materials } = useGLTF(
    "/3d model/bag-transformed.glb"
  );
  // const bag = useRef()
  // const scroll = useScroll()
  // const tl =useRef()
  // useFrame((state,delta)=>{
  //     tl.current.seek(scroll.offset*tl.current.duration())
  // })
  
  // useLayoutEffect(() => {
  //   tl.current = gsap.timeline({ defaults: { duration: 2, ease: "power1.inOut" } })
  //     .to(bag.current.scale, { x: 2, y: 2, z: 2 }, 0) // Scale up to 2x
  //     .to(bag.current.rotation, { y: -1 }, "<") // Start rotation animation at the same time as scaling
  //     .to(bag.current.position, { x: -1 }, "<") // Start position animation at the same time as scaling
  
  //     .to(bag.current.rotation, { y: 1 }, 3)
  //     .to(bag.current.position, { x: -1 }, 3)
  
  //     .to(bag.current.rotation, { y: 0 }, 4)
  //     .to(bag.current.rotation, { x: 1 }, 4)
  //     .to(bag.current.position, { x: 0 }, 4)
  //     .to(bag.current.scale, { x: 1, y: 1, z: 1 }, 4); // Scale back to original size
  // }, []);
  
  return (
    <group {...props} dispose={null}
    //  ref={bag}
     >
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.wire_204204204_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={15}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.wire_204204204_2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={15}
      />
    </group>
  );
}

useGLTF.preload("/3d model/bag-transformed.glb");
