/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 blacksuit.glb --transform 
Files: blacksuit.glb [30.13MB] > C:\Users\HP\Desktop\New folder (5)\public\3d model\blacksuit-transformed.glb [2.67MB] (91%)
Author: deymar (https://sketchfab.com/deymar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-set-of-clothes-maniacs-cloak-high-poly-880bea7e2614458194e72acebe23f652
Title: a set of clothes "maniac's cloak" HIGH POLY
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
export function BlacksuitModel(props) {
  const { nodes, materials } = useGLTF(
    "/3d model/blacksuit-transformed.glb"
  );
  return (
    <group {...props} dispose={null} position={[0, -3, 0]} scale={0.04}>
      <mesh
        geometry={nodes.jcet_lambert1_0.geometry}
        material={materials.lambert1}
      />
    </group>
  );
}

useGLTF.preload("/3d model/blacksuit-transformed.glb");
