/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 perfume.glb --transform 
Files: perfume.glb [4.94MB] > C:\Users\HP\Desktop\New folder (5)\public\3d model\perfume-transformed.glb [362.12KB] (93%)
Author: B/W Productshots (https://sketchfab.com/bw-productshots)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/n19-chanel-paris-eau-de-parfum-81b837b4ad9b41b6a48a1b2950d90981
Title: N°19 Chanel Paris (Eau De Parfum)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PerfumeModel(props) {
  const { nodes, materials } = useGLTF(
    "/3d model/perfume-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.PaletteMaterial001}
        position={[-0.003, -0.007, -0.002]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.CC_Logo}
        position={[-0.003, -0.007, -0.002]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.003, -0.007, -0.002]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.Made_In}
        position={[-0.003, -0.007, -0.002]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Plastic_White_-_Glossy"]}
        position={[-0.003, -0.007, -0.002]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.PaletteMaterial003}
        position={[-0.003, -0.007, -0.002]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
    </group>
  );
}

useGLTF.preload("/3d model/perfume-transformed.glb");
